#pragma once

#include "Interfaces.h"
#include "GeneralDefinitions.h"
#include "GeneralStructures.h"
#include "ArrayClasses.h"
#include "IndexClass.h"
#include "GameStrings.h"

class TechnoClass;
class HouseClass;
class CRCEngine;

struct StorageClass
{
	float GetAmount(int index) const
		{ JMP_THIS(0x6C9680); }

	float GetTotalAmount() const
		{ JMP_THIS(0x6C9650); }

	float AddAmount(float amount, int index)
		{ JMP_THIS(0x6C9690); }

	float RemoveAmount(float amount, int index)
		{ JMP_THIS(0x6C96B0); }

	int GetTotalValue() const
		{ JMP_THIS(0x6C9600); }

	float Tiberium1;
	float Tiberium2;
	float Tiberium3;
	float Tiberium4;
};
//---

/*!
* @brief The AbstractClass is the base class of all game objects.
*/
class NOVTABLE AbstractClass : public IPersistStream, public IRTTITypeInfo, public INoticeSink, public INoticeSource
{
public:
	/*!
	* @brief use only for setting virtual tables in missing noinit ctors
	*/
	struct __declspec(align(sizeof(uintptr_t))) vtables_t
	{
		uintptr_t IPersistStream;
		uintptr_t IRTTITypeInfo;
		uintptr_t INoticeSink;
		uintptr_t INoticeSource;

		constexpr vtables_t() noexcept :
			  IPersistStream(0x7E1F50)
			, IRTTITypeInfo(0x7E1F34)
			, INoticeSink(0x7E1F2C)
			, INoticeSource(0x7E1F24)
		{}

		__forceinline void init(AbstractClass* instance) { memcpy(instance, this, sizeof(vtables_t)); }
	};
	static inline vtables_t vtables{};
public:
	static constexpr uintptr_t AbsVTable = 0x7E1F50;
	static constexpr RTTIType AbsID = RTTIType::Abstract;
	static constexpr size_t ClassSize = 0x24;

	DEFINE_POINTER(DynamicVectorClass<AbstractClass*>, Array, 0xB0F720u)
	DEFINE_REFERENCE((IndexClass<int, int>), TargetIndex, 0xB0E840u)

	const char* GetRTTIName() const { return AbstractClass::GetRTTIName(this->KindOf()); }
	static const char* GetRTTIName(RTTIType abs) JMP_THIS(0x40DCB0);
	/*!
	* @brief generated by IRTTIInfo::Create_ID through an amazingly simple sequence of return ++ScenarioClass::Instance->UniqueID;
	*/
	DWORD UniqueID;
	/*!
	* @brief Flags, see AbstractFlags enum in GeneralDefinitions.
	*/
	AbstractFlags AbstractFlags;
	DWORD unknown_18;
	LONG RefCount;
	/*!
	* @brief for IPersistStream.
	*/
	bool Dirty;
	PROTECTED_PROPERTY(BYTE, padding_21[0x3]);
public:
	void __stdcall Issue() override JMP_STD(0x410590);
	bool __stdcall Respond(DWORD command) override JMP_STD(0x410580);

	RTTIType __stdcall What_Am_I() const override JMP_STD(0x410210);
	int __stdcall Fetch_ID() const override JMP_STD(0x410220);
	void __stdcall Create_ID() override JMP_STD(0x410230);

	/*00:0x00*/
	HRESULT __stdcall QueryInterface(REFIID iid, void** ppvObject) override JMP_STD(0x410260);
	/*01:0x04*/
	ULONG __stdcall AddRef() override JMP_STD(0x410300);
	/*02:0x08*/
	ULONG __stdcall Release() override JMP_STD(0x410310);
	/*04:0x10*/
	HRESULT __stdcall IsDirty() override JMP_STD(0x410450);
	/*07:0x1C*/
	HRESULT __stdcall GetSizeMax(ULARGE_INTEGER* pcbSize) override JMP_STD(0x4103E0);

	/*08:0x20*/
	virtual ~AbstractClass(/*DestructorFlags flags*/) JMP_THIS(0x4105A0);

	/*!
	* @note original_name Init
	* @note vtable_index 09:0x24
	* @note address 0x410470
	*/
	virtual void Init() JMP_THIS(0x410470);

	/*!
	* @brief Invalidate pointers to instance (clear fields which containing it). Broadcast.
	* @note original_name Detach
	* @note vtable_index 10:0x28
	* @note address 0x410480
	*/
	virtual void InvalidatePointer(AbstractClass* instance, bool all = true) JMP_THIS(0x410480);

	/*!
	* @note original_name Kind_Of
	* @note vtable_index 11:0x2C
	* @note address 0x0
	*/
	virtual RTTIType KindOf() const = 0;

	/*!
	* @note original_name Size_Of
	* @note vtable_index 12:0x30
	* @note address 0x0
	*/
	virtual int SizeOf() const = 0;

	/*!
	* @note original_name Compute_CRC
	* @note vtable_index 13:0x34
	* @note address 0x410410
	*/
	virtual void ComputeCRC(CRCEngine& crc) const JMP_THIS(0x410410);

	/*!
	* @brief returns owner house ID (index)
	* @note original_name Owner
	* @note vtable_index 14:0x38
	* @note address 0x410490
	*/
	virtual int GetOwner() const JMP_THIS(0x410490);

	/*!
	* @brief returns owner house
	* @note original_name Owning_House
	* @note vtable_index 15:0x3C
	* @note address 0x4104A0
	*/
	virtual HouseClass* OwningHouse() const JMP_THIS(0x4104A0);

	/*!
	* @note original_name Get_Heap_ID
	* @note vtable_index 16:0x40
	* @note address 0x4104B0
	*/
	virtual int GetArrayIndex() const JMP_THIS(0x4104B0);

	/*!
	* @note original_name Is_Inactive
	* @note vtable_index 17:0x44
	* @note address 0x410440
	*/
	virtual bool IsInactive() const JMP_THIS(0x410440);

	/*!
	* @note original_name Center_Coord
	* @note vtable_index 18:0x48
	* @note address 0x4104C0
	*/
	virtual Coordinate Center() const JMP_THIS(0x4104C0);

	/*!
	* @brief Where this is moving, or a building's dock for a techno. iow, a rendez-vous point.
	* @note original_name Target_Coord
	* @note vtable_index 19:0x4C
	* @note address 0x4104F0
	*/
	virtual Coordinate GetDestination(TechnoClass* pDocker = nullptr) const JMP_THIS(0x4104F0);
	
	/*!
	* @note original_name On_Ground
	* @note vtable_index 20:0x50
	* @note address 0x410520
	*/
	virtual bool IsOnGround() const JMP_THIS(0x410520);

	/*!
	* @note original_name In_Air
	* @note vtable_index 21:0x54
	* @note address 0x410530
	*/
	virtual bool InAir() const JMP_THIS(0x410530);

	/*!
	* @brief DO NOT USE THIS WHEN YOU NEED A CENTER. This is some specific-special functions. It used in BulletClass to get coords of the targets. It's overriden only in CellClass.
	* @note original_name Get_Coord
	* @note vtable_index 22:0x58
	* @note address 0x410540
	*/
	virtual Coordinate TargetingCoord() const JMP_THIS(0x410540);
	/*!
	* @brief Process object per frame.
	* @note original_name AI
	* @note vtable_index 23:0x5C
	* @note address 0x410570
	*/
	virtual void AI() JMP_THIS(0x410570);

	static void __fastcall DetachFromAll(AbstractClass* instance, bool all = true) JMP_THIS(0x7258D0);
	void DetachFromAll(bool all = true) { DetachFromAll(this, all); }

	static void __fastcall RemoveAllInactive() JMP_STD(0x725C70);

	/*! @brief It is not VIRTUAL <IPersistStream::Load> functions, it is proxy which used at EACH override of virtual. */
	HRESULT __stdcall Load(IStream* stream) JMP_THIS(0x410380);
	/*! @brief It is not VIRTUAL <IPersistStream::Save> functions, it is proxy which used at EACH override of virtual. */
	HRESULT __stdcall Save(IStream* stream, int32_t fClearDirty) JMP_THIS(0x410320);
	/*! @brief Return if this is any ancestor of TechnoClass otherwise return null. USED IN ACTION SELECTION.*/
	TechnoClass* AsTechno() JMP_THIS(0x40DD20);
	/*! @brief Return if this is any ancestor of TechnoClass otherwise return null. USED IN DAMAGE/SELECTION/PER CELL PROCESS.*/
	TechnoClass* _AsTechno() JMP_THIS(0x40DD70);

	constexpr bool operator<(const AbstractClass &rhs) const { return this->UniqueID < rhs.UniqueID; }

protected:
	/*! @brief FAKE CTOR */
	explicit __forceinline AbstractClass(fake_noinit_t) noexcept {}
	AbstractClass() : AbstractClass(fake_noinit_t{}) JMP_THIS(0x410170);
	AbstractClass(noinit_t) noexcept : AbstractClass(fake_noinit_t{}) JMP_THIS(0x4101C0);
};
static_assert(sizeof(AbstractClass) == AbstractClass::ClassSize);

template<typename T>
concept HasAbsVTable = std::is_base_of_v<AbstractClass,T> && requires {
	{ T::AbsVTable }-> std::convertible_to<uintptr_t>;
};
