#pragma once

#include "Interfaces.h"
#include "GeneralDefinitions.h"
#include "GeneralStructures.h"
#include "ArrayClasses.h"
#include "IndexClass.h"
#include "GameStrings.h"

//forward declarations
class TechnoClass;
class HouseClass;
class CRCEngine;

struct StorageClass
{
	float GetAmount(int index) const
		{ JMP_THIS(0x6C9680); }

	float GetTotalAmount() const
		{ JMP_THIS(0x6C9650); }

	float AddAmount(float amount, int index)
		{ JMP_THIS(0x6C9690); }

	float RemoveAmount(float amount, int index)
		{ JMP_THIS(0x6C96B0); }

	int GetTotalValue() const
		{ JMP_THIS(0x6C9600); }

	float Tiberium1;
	float Tiberium2;
	float Tiberium3;
	float Tiberium4;
};
//---

/*!
* @brief The AbstractClass is the base class of all game objects.
*/
class NOVTABLE AbstractClass : public IPersistStream, public IRTTITypeInfo, public INoticeSink, public INoticeSource
{
public:
	static constexpr uintptr_t AbsVTable = 0x7E1F50;
	static constexpr RTTIType AbsID = RTTIType::Abstract;

	static constexpr constant_ptr<DynamicVectorClass<AbstractClass*>, 0xB0F720u> const Array{};
	static constexpr reference<IndexClass<int, int>, 0xB0E840u> const TargetIndex{};

	const char* GetRTTIName() const { return AbstractClass::GetRTTIName(this->KindOf()); }
	static const char* GetRTTIName(RTTIType abs)
	{
		constexpr reference<std::pair<const char*, RTTIType>, 0x816EE0, 74> name_val_pairs;
		for (const auto& [name, rtti] : name_val_pairs())
		{
			if (rtti == abs)
				return name;
		}
		return nullptr;
	}
public:
	/*!
	* @brief generated by IRTTIInfo::Create_ID through an amazingly simple sequence of return ++ScenarioClass::Instance->UniqueID;
	*/
	DWORD UniqueID;
	/*!
	* @brief Flags, see AbstractFlags enum in GeneralDefinitions.
	*/
	AbstractFlags AbstractFlags;
	DWORD unknown_18;
	LONG RefCount;
	/*!
	* @brief for IPersistStream.
	*/
	bool Dirty;
	PROTECTED_PROPERTY(BYTE, padding_21[0x3]);
public:
	virtual RTTIType __stdcall What_Am_I() const override JMP_THIS(0x410210);
	virtual int __stdcall Fetch_ID() const override JMP_THIS(0x410220);
	virtual void __stdcall Create_ID() override JMP_THIS(0x410230);

	/*00:0x00*/virtual HRESULT __stdcall QueryInterface(REFIID iid, void** ppvObject) override JMP_THIS(0x410260);
	/*01:0x04*/virtual ULONG __stdcall AddRef() override JMP_THIS(0x410300);
	/*02:0x08*/virtual ULONG __stdcall Release() override JMP_THIS(0x410310);
	/*04:0x10*/virtual HRESULT __stdcall IsDirty() override JMP_THIS(0x410450);
	/*07:0x1C*/virtual HRESULT __stdcall GetSizeMax(ULARGE_INTEGER* pcbSize) override JMP_THIS(0x4103E0);

	/*08:0x20*/virtual ~AbstractClass(/*DestructorFlags flags*/) JMP_THIS(0x4105A0);
	/*09:0x24*/virtual void Init() JMP_THIS(0x410470);
	/*!
	* @brief Invalidate pointers to instance (clear fields which containing it). Broadcast.
	* @note vtable_index 10:0x28
	*/
	virtual void Detach(AbstractClass* instance, bool all = true) JMP_THIS(0x410480);
	/*11:0x2C*/virtual RTTIType KindOf() const = 0;
	/*12:0x30*/virtual int SizeOf() const = 0;
	/*13:0x34*/virtual void ComputeCRC(CRCEngine& crc) const JMP_THIS(0x410410);
	/*14:0x38*/virtual int Owner() const  JMP_THIS(0x410490);
	/*15:0x3C*/virtual HouseClass* OwningHouse() const JMP_THIS(0x4104A0);
	/*16:0x40*/virtual int ArrayIndex() const JMP_THIS(0x4104B0);
	/*17:0x44*/virtual bool IsInactive() const JMP_THIS(0x410440);
	/*18:0x48*/virtual Coordinate Center() const JMP_THIS(0x4104C0);
	/*!
	* @brief Where this is moving, or a building's dock for a techno. iow, a rendez-vous point.
	* @note vtable_index 19:0x4C
	*/
	virtual Coordinate Destination(TechnoClass* pDocker = nullptr) const JMP_THIS(0x4104F0);
	/*20:0x50*/virtual bool OnGround() const JMP_THIS(0x410520);
	/*21:0x54*/virtual bool InAir() const JMP_THIS(0x410530);
	/*!
	* @brief DO NOT USE THIS WHEN YOU NEED A CENTER. This is some specific-special functions. It used in BulletClass to get coords of the targets. It's overriden only in CellClass.
	* @note vtable_index 22:0x58
	*/
	virtual Coordinate TargetingCoord() const JMP_THIS(0x410540);
	/*23:0x5C*/virtual void AI() JMP_THIS(0x410570);

	static void __fastcall DetachFromAll(AbstractClass* instance, bool all = true) JMP_THIS(0x7258D0); 
	inline void DetachFromAll(bool all = true) { DetachFromAll(this, all); }

	inline static void __fastcall RemoveAllInactive() JMP_STD(0x725C70);

	/*! @brief It is not VIRTUAL <IPersistStream::Load> functions, it is proxy which used at EACH override of virtual. */
	inline HRESULT Load(IStream* stream) JMP_THIS(0x410380);
	/*! @brief It is not VIRTUAL <IPersistStream::Save> functions, it is proxy which used at EACH override of virtual. */
	inline HRESULT Save(IStream* stream, int32_t fClearDirty) JMP_THIS(0x410320);
	/*! @brief Return if this is any ancestor of TechnoClass otherwise return null. USED IN ACTION SELECTION.*/
	inline TechnoClass* AsTechno() JMP_THIS(0x40DD20);
	/*! @brief Return if this is any ancestor of TechnoClass otherwise return null. USED IN DAMAGE/SELECTION/PER CELL PROCESS.*/
	inline TechnoClass* _AsTechno() JMP_THIS(0x40DD70);

	inline bool operator<(const AbstractClass &rhs) const { return this->UniqueID < rhs.UniqueID; }

protected:
	/*! @brief FAKE CTOR */
	explicit __forceinline AbstractClass(fake_noinit_t) noexcept {}
	AbstractClass(noinit_t) : AbstractClass(fake_noinit_t{}) JMP_THIS(0x4101C0);
	AbstractClass() : AbstractClass(fake_noinit_t{}) JMP_THIS(0x410170);
};

template<typename T>
concept HasAbsVTable = std::is_base_of_v<AbstractClass,T> && requires {
	{ T::AbsVTable }-> std::convertible_to<uintptr_t>;
};
